apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-server
  labels:
    app: fastapi-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      name: fastapi-app
      labels:
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-server
          image: my-fastapi-app:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8090
      restartPolicy: Always
      
