apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30080
  type: NodePort
  